version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: fraud_postgres
    environment:
      POSTGRES_USER: mlops_user
      POSTGRES_PASSWORD: mlops_password
      POSTGRES_DB: fraud_detection
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mlops_user -d fraud_detection"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fraud-network

  redis:
    image: redis:7-alpine
    container_name: fraud_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - fraud-network

  fastapi:
    build:
      context: ./src/serving
      dockerfile: Dockerfile
    container_name: fraud_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://mlops_user:mlops_password@postgres:5432/fraud_detection
      REDIS_URL: redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src/serving:/app
    networks:
      - fraud-network

volumes:
  postgres_data:
  redis_data:

networks:
  fraud-network:
    driver: bridge
